spring:
  application:
    name: easy-spring-auth
  view-component:
    local-development: true
#org:
#  eclipse:
#    store:
#      root: de.tschuehly.easy.spring.auth.store.Root
#      storage-directory: ./storage
gg:
  jte:
    developmentMode: true
htmx:
  endpoint:
    annotationClassesToScan:
      - org.springframework.stereotype.Controller
      - de.tschuehly.spring.viewcomponent.core.component.ViewComponent